# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myMemo', '0002_auto_20170310_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicmemo',
            old_name='owner',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='privateMemo',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='publicMemo',
        ),
        migrations.RemoveField(
            model_name='privatememo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='publicmemo',
            name='photo',
        ),
        migrations.AddField(
            model_name='privatememo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatememo',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
