# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMemo', '0004_publicmemo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicmemo',
            name='owner',
        ),
    ]
